# Site settings
title: My Awesome Site
description: This is my personal website hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://username.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Optional features
markdown: kramdown
highlighter: rouge
permalink: pretty

# Social links (you can add your own)
twitter_username: johndoe123
github_username:  johndoe
